version: 2.1

jobs:
  ios:
    macos:
      xcode: 14.1.0
    steps:
      - checkout
      - run:
          name: Setup Simulator
          command: |
            xcrun simctl create iPhone14Pro com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro com.apple.CoreSimulator.SimRuntime.iOS-16-1 > deviceid.txt
            xcrun simctl boot $(cat deviceid.txt)
            echo "Booted a devier with ID $(cat deviceid.txt)"
      - run:
          name: Setup Appium
          command: |
            npm install -g appium
            appium -v
            appium driver install xcuitest
            appium --log-timestamp --log-no-colors --log appium-log.txt &> /dev/null &
            until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/sessions); do
              echo "retrying appium server status..."
              sleep 5
            done
            echo "Appium seriver started..."
      - run:
          name: Setup Maven
          command: |
            brew install maven

      - run:
          name: Run E2e
          command: |
            echo "Appium sessions $(curl http://127.0.0.1:4723/sessions)"
            SIMULATOR_UDID=$(cat deviceid.txt) TEST_APP_PATH="./apps/mobileapp.app" mvn clean test

workflows:
  Run E2E Tests:
    jobs:
      - ios