name: IOS E2E tests

on:
  push:
    branches: [ "main" ]

jobs:
  ios:
    runs-on: macos-latest

    env:
      TEST_APP_PATH: './apps/mobileapp.app'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install iOS Simulator
        run: |
          xcrun simctl create iPhone13Pro com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro com.apple.CoreSimulator.SimRuntime.iOS-16-2 > udid.txt
          xcrun simctl boot $(cat udid.txt)
          echo "SIMULATOR_UDID=$(cat udid.txt)" >> $GITHUB_ENV
          echo "Booted a device with UDID $SIMULATOR_UDID"

      - name: Setup appium
        run: |
          npm install -g appium
          appium -v
          appium driver install xcuitest
          appium --log-timestamp --log-no-colors --log appium-log.txt &> /dev/null &

      - name: Wait for appium
        run: |
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/sessions); do
           sleep 5
          done

      - name: Run E2E tests
        run: mvn -q clean test

      - name: Upload Appium logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: appium-log.txt
