name: IOS E2E tests

on:
  push:
    branches: [ "main" ]

jobs:
  ios:
    runs-on: macos-latest

    env:
      TEST_APP_PATH: './apps/mobileapp.app'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Check simulator
        run: xcrun simctl list available

      - name: Build with Maven
        run: mvn clean test